spring:
  application:
    name: product-manager

  datasource:
#      url: jdbc:h2:file:/data/product-manager
#      url: jdbc:postgresql://db:5432/product_manager
      url: jdbc:postgresql://localhost:5432/product_manager
      username: postgres
#      username: sa
      password: password
#      driverClassName: org.h2.Driver
      driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
#    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

#    ddl-auto= <create | create-drop | update | validate | none>
#    hibernate.ddl-auto: update
    hibernate:
      ddl-auto: create-drop #<create | create-drop | update | validate | none>
      transaction:
        jta:
          platform: org.hibernate.engine.transaction.internal.jta.JtaPlatformInitiator
#    database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

  h2:
      console:
        enabled: true
        path: /h2-console
        settings.trace: false
        settings.web-allow-others: false

